### ISSUE TITLE
UnicodeDecodeError when parsing non-utf8 characters

### ISSUE THREAD

**Issue by flyasfish** [josegonzalez/python-beaver#158]
This is to continue Issue #104 which has been fixed in v29 thanks for the effort Jose. However I still face this UnicodeDecodeError in the following scenario. My config is like follows

[/home/infra/logstash/test/invalid_chars.log]
type: test_log

Scenario 1:
When start beaver, the invalid_chars.log file already have non-utf8 chars in the file, then I see following lines in beaver log with debug mode

[2013-06-04 11:01:30,973] INFO    [40020007g117e6] - watching logfile /home/infra/logstash/test/invalid_chars.log
[2013-06-04 11:01:30,974] DEBUG   [40020007g117e6] - getting start position /home/infra/logstash/test/invalid_chars.log
[2013-06-04 11:01:30,975] DEBUG   [40020007g117e6] - getting end position for /home/infra/logstash/test/invalid_chars.log
[2013-06-04 11:01:30,975] DEBUG   [40020007g117e6] - UnicodeDecodeError raised for /home/infra/logstash/test/invalid_chars.log with encoding utf_8
[2013-06-04 11:01:30,977] DEBUG   [40020007g117e6] - line count 1 for /home/infra/logstash/test/invalid_chars.log

Then if I add more lines with non-utf8 chars like 0xbf beaver can parse it successfully.

Scenario 2:
However when start beaver,  the invalid_chars.log file does not have non-utf8 chars in the file, for example if the file is empty, I see following lines in beaver log with debug mode

[2013-06-04 11:04:53,086] INFO    [40020007g117e6] - watching logfile /home/infra/logstash/test/invalid_chars.log
[2013-06-04 11:04:53,087] DEBUG   [40020007g117e6] - getting start position /home/infra/logstash/test/invalid_chars.log
[2013-06-04 11:04:53,088] DEBUG   [40020007g117e6] - getting end position for /home/infra/logstash/test/invalid_chars.log
[2013-06-04 11:04:53,088] DEBUG   [40020007g117e6] - line count 0 for /home/infra/logstash/test/invalid_chars.log

Then if I add more lines with non-utf8 chars like 0xbf beaver will throw exception and stuck, after 60 seconds beaver will stop.

[2013-06-04 11:05:09,930] DEBUG   Iteration took 0.000685
Traceback (most recent call last):
  File "/home/infra/logstash/py_ve/py_ve/bin/beaver", line 31, in <module>
    worker_run(args)
  File "/home/infra/logstash/py_ve/py_ve/lib/python2.7/site-packages/beaver/dispatcher/worker.py", line 69, in run
    worker.loop()
  File "/home/infra/logstash/py_ve/py_ve/lib/python2.7/site-packages/beaver/worker/worker.py", line 99, in loop
    self._run_pass(fid, data['file'])
  File "/home/infra/logstash/py_ve/py_ve/lib/python2.7/site-packages/beaver/worker/worker.py", line 117, in _run_pass
    data = file.read(4096)
  File "/home/infra/logstash/py_ve/py_ve/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbf in position 84: invalid start byte
[2013-06-04 11:05:14,037] DEBUG   No data
[2013-06-04 11:05:19,027] DEBUG   No data
[2013-06-04 11:05:24,017] DEBUG   No data
[2013-06-04 11:05:29,007] DEBUG   No data
[2013-06-04 11:05:33,996] DEBUG   No data
[2013-06-04 11:05:38,986] DEBUG   No data
[2013-06-04 11:05:43,976] DEBUG   No data
[2013-06-04 11:05:48,966] DEBUG   No data
[2013-06-04 11:05:53,956] DEBUG   No data
[2013-06-04 11:05:58,945] DEBUG   No data
[2013-06-04 11:06:03,935] DEBUG   No data
[2013-06-04 11:06:08,928] DEBUG   No data
[2013-06-04 11:06:13,916] DEBUG   No data
[2013-06-04 11:06:13,917] INFO    Queue timeout of "60" seconds exceeded, stopping queue

**Comment by JamieCressey** [comment]
#353
