### ISSUE TITLE
Amazon SQS 413 Request Entity Too Large

### ISSUE THREAD

**Issue by ssstonebraker** [josegonzalez/python-beaver#204]
I'm seeing this on multiple beaver instances:

    [2013-10-25 00:52:42,997] ERROR   Exception occurred sending batch to SQS queue
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/beaver/transports/sqs_transport.py", line 58, in _send_message_batch
        result = self._queue.write_batch(message_batch)
      File "/usr/local/lib/python2.7/dist-packages/boto/sqs/queue.py", line 239, in write_batch
        return self.connection.send_message_batch(self, messages)
      File "/usr/local/lib/python2.7/dist-packages/boto/sqs/connection.py", line 281, in send_message_batch
        queue.id, verb='POST')
      File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1062, in get_object
        raise self.ResponseError(response.status, response.reason, body)
    SQSError: SQSError: 413 Request Entity Too Large
    None
    [2013-10-25 00:52:42,997] INFO    Caught transport exception, reconnecting in 2187 seconds

**Comment by Logicalj** [comment]
Is there any upper limit as well on payload... like we can't process upload with size exceeding 1 MB?

**Comment by JamieCressey** [comment]
SQS message size limited merged and released.
