### ISSUE TITLE
Invalid logstash_version

### ISSUE THREAD

**Issue by carlskii** [josegonzalez/python-beaver#249]
Hi,

I just installed Beaver, but seem to continually get errors. e.g.
beaver --format json

```
Traceback (most recent call last):
  File "/usr/local/bin/beaver", line 31, in <module>
    worker_run(args)
  File "/usr/local/lib/python2.7/dist-packages/beaver/dispatcher/worker.py", line 19, in run
    raise LookupError("Invalid logstash_version")
LookupError: Invalid logstash_version
```

Then if try to use a config file:

```
[beaver]
zeromq_address: tcp://indexer:5556

# logstash indexer config:
input {
  zeromq {
    type => 'shipper-input'
    mode => 'server'
    topology => 'pushpull'
    address => 'tcp://*:5556'
  }
}
```

I get:

```
server1:~$ beaver -c /etc/beaver/conf -m connect -t zmq
Traceback (most recent call last):
  File "/usr/local/bin/beaver", line 31, in <module>
    worker_run(args)
  File "/usr/local/lib/python2.7/dist-packages/beaver/dispatcher/worker.py", line 17, in run
    beaver_config = BeaverConfig(args, logger=logger)
  File "/usr/local/lib/python2.7/dist-packages/beaver/config.py", line 153, in __init__
    self._parse(args)
  File "/usr/local/lib/python2.7/dist-packages/beaver/config.py", line 439, in _parse
    config_parser=self._config_parser
  File "/usr/local/lib/python2.7/dist-packages/conf_d/__init__.py", line 28, in __init__
    self.parse()
  File "/usr/local/lib/python2.7/dist-packages/conf_d/__init__.py", line 74, in parse
    configs = self._parse_section(path=self._path, defaults=self._main_defaults, parser=self._main_parser, only_section=self._name)
  File "/usr/local/lib/python2.7/dist-packages/conf_d/__init__.py", line 110, in _parse_section
    if len(config_parser.read(path)) != 1:
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/local/lib/python2.7/dist-packages/beaver/glob_safe_config_parser.py", line 70, in _read
    e = ParsingError(fpname)
NameError: global name 'ParsingError' is not defined
```

**Comment by JamieCressey** [comment]
I'm unable to replicate this locally, feel free to reopen this if you're still seeing this on the latest release.
