### ISSUE TITLE
ImportError: This platform lacks a functioning sem_open implementation

### ISSUE THREAD

**Issue by StefanSa** [josegonzalez/python-beaver#283]
Hi i get on FreeBSD 10.1 this error message:

```javascript
[root@www1 /var/log/beaver]# beaver -c /usr/local/etc/beaver/beaver.conf
Traceback (most recent call last):
  File "/usr/local/bin/beaver", line 31, in <module>
    worker_run(args)
  File "/usr/local/lib/python2.7/site-packages/beaver/dispatcher/worker.py", line 24, in run
    queue = multiprocessing.Queue(beaver_config.get('max_queue_size'))
  File "/usr/local/lib/python2.7/multiprocessing/__init__.py", line 217, in Queue
    from multiprocessing.queues import Queue
  File "/usr/local/lib/python2.7/multiprocessing/queues.py", line 48, in <module>
    from multiprocessing.synchronize import Lock, BoundedSemaphore, Semaphore, Condition
  File "/usr/local/lib/python2.7/multiprocessing/synchronize.py", line 59, in <module>
    " function, see issue 3770.")
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```
any helpe here ?

**Comment by nbari** [comment]
On a real operating system like FreeBSD, to avoid this error you should rebuild lang/python27 with SEM.
