### ISSUE TITLE
Installation problem on Ubuntu 12.04: ImportError: No module named version

### ISSUE THREAD

**Issue by orion-raft** [josegonzalez/python-beaver#286]
When trying to install beaver on Ubuntu 12.04, I get the following error:

```
root@dev:beaver# pip install beaver==33.0.0
Collecting beaver==33.0.0
  Downloading Beaver-33.0.0.tar.gz (67kB)
    100% |################################| 69kB 12.6MB/s
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-KwMc_w/beaver/setup.py", line 77, in <module>
        install_requires=requirements,
      File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "<string>", line 12, in replacement_run
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2310, in load
        return self.resolve()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named version
    Complete output from command python setup.py egg_info:
    running egg_info

    creating pip-egg-info/Beaver.egg-info

    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-KwMc_w/beaver/setup.py", line 77, in <module>

        install_requires=requirements,

      File "/usr/lib/python2.7/distutils/core.py", line 152, in setup

        dist.run_commands()

      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

        self.run_command(cmd)

      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

        cmd_obj.run()

      File "<string>", line 12, in replacement_run

      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2310, in load

        return self.resolve()

      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in resolve

        module = __import__(self.module_name, fromlist=['__name__'], level=0)

    ImportError: No module named version

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-KwMc_w/beaver
root@dev:beaver# pip list
apparmor (2.7.102)
apt-xapian-index (0.44)
chardet (2.0.1)
command-not-found (0.2.44)
docutils (0.12)
GnuPGInterface (0.3.2)
httplib2 (0.7.2)
Landscape-Client (13.7.3)
lockfile (0.10.2)
PAM (0.4.2)
pip (6.0.6)
pycrypto (2.4.1)
pyOpenSSL (0.12)
pyserial (2.5)
python-apt (0.8.3ubuntu7.2)
python-daemon (2.0.3)
redis (2.10.3)
setuptools (11.3.1)
simplejson (2.3.2)
Twisted-Core (11.1.0)
ufw (0.31.1-1)
virtualenv (12.0.5)
```

**Comment by josegonzalez** [comment]
Can you paste your setuptools and distribute versions?

**Comment by orion-raft** [comment]
According to `pip list` I am running setuptools version 11.3.1 and distribute is not installed.

**Comment by josegonzalez** [comment]
Did setuptools just break something? @vigoatrook this might be related to your error?

**Comment by vigoatrook** [comment]
It looks similar to mine. I installed pip and setuptools using apt-get install python-setuptools.
*pip list* throws an assertion error after listing python-daemon.

**Comment by josegonzalez** [comment]
Odd that it stopped working, it's definitely installed fine for me on both 12.04 and 14.04 in the past, and I haven't changed that package since it's initial release.

**Comment by gfloyd** [comment]
I just ran into this same issue. Looks like it's due to python-daemon upgrading to 2.0.3, and >= 1.5.2 is specified in requirements/base.txt.

I just did:

```
pip uninstall python-daemon
pip install python-daemon==1.6.1
```

And then `pip install beaver==33` worked fine.

**Comment by vigoatrook** [comment]
@josegonzalez  uninstalling and resinstalling python-daemon (the suggestion above) also worked for me!

**Comment by orion-raft** [comment]
@gfloyd That worked for me too! Thank you very much.

**Comment by josegonzalez** [comment]
Shouldnt it stay at 1.5.x?

**Comment by gfloyd** [comment]
I had a number of other machines with beaver installed that had python-daemon 1.6.1 and were working fine (that's how I noticed the difference), so I just went with that. requirements.txt should probably be more strict, though!

**Comment by josegonzalez** [comment]
Pull requests accepted! :)

**Comment by gfloyd** [comment]
Done and done :)

**Comment by josegonzalez** [comment]
I'll try and make a release this weekend - and hopefully give beaver a bit of love, I've been lacking on time for it :(

**Comment by josegonzalez** [comment]
https://github.com/josegonzalez/python-beaver/releases/tag/33.1.0
