### ISSUE TITLE
NameError: global name 'ParsingError' is not defined

### ISSUE THREAD

**Issue by sharjeelsayed** [josegonzalez/python-beaver#316]
Traceback (most recent call last):
  File "/usr/local/bin/beaver", line 31, in <module>
    worker_run(args)
  File "/usr/local/lib/python2.7/site-packages/beaver/dispatcher/worker.py", line 17, in run
    beaver_config = BeaverConfig(args, logger=logger)
  File "/usr/local/lib/python2.7/site-packages/beaver/config.py", line 171, in __init__
    self._parse(args)
  File "/usr/local/lib/python2.7/site-packages/beaver/config.py", line 461, in _parse
    config_parser=self._config_parser
  File "/usr/local/lib/python2.7/site-packages/conf_d/__init__.py", line 28, in __init__
    self.parse()
  File "/usr/local/lib/python2.7/site-packages/conf_d/__init__.py", line 74, in parse
    configs = self._parse_section(path=self._path, defaults=self._main_defaults, parser=self._main_parser, only_section=self._name)
  File "/usr/local/lib/python2.7/site-packages/conf_d/__init__.py", line 110, in _parse_section
    if len(config_parser.read(path)) != 1:
  File "/usr/local/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/local/lib/python2.7/site-packages/beaver/glob_safe_config_parser.py", line 70, in _read
    e = ParsingError(fpname)
NameError: global name 'ParsingError' is not defined

**Comment by josegonzalez** [comment]
Can you try installing 6d021289898b2287b0f113593de7d4995a38133f and seeing if it fixes your issue? Also, you have a parse error in your config.

**Comment by JamieCressey** [comment]
Closing due to inactivity. Please reopen if this is still a problem.
